[tools]
bat = "latest"
bun = "latest"
lua-language-server = "latest"
node = "latest"
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
numbat = "latest"
"pipx:pyright" = "latest"
"pipx:systemd-language-server" = "latest"
python = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
uv = "latest"
watchexec = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[settings.npm]
bun = true

[settings.pipx]
uvx = true
